[SERVICE]
    Flush            30
    Daemon           off
    Log_Level        ${LOG_LEVEL}
    HTTP_Server      On
    HTTP_Listen      0.0.0.0
    HTTP_PORT        2020
    Health_Check     On
    scheduler.base   10
    scheduler.cap    60

[OUTPUT]
    Name            cloudwatch_logs
    Match           *
    Region          eu-west-2
    Log_Group_Name  ${LOG_GROUP_NAME}
    Log_Stream_Name ${LOG_STREAM_NAME}
    Retry_Limit     5
    Storage.Total_Limit_Size 100M
    workers         1

[OUTPUT]
    Name            http
    Match           *
    Host            ${LOGSTASH_HOST}
    Port            ${LOGSTASH_PORT}
    Format          json_lines
    tls             On
    tls.verify      Off
    Retry_Limit     5
    Storage.Total_Limit_Size 100M
